<a href="https://colab.research.google.com/github/PritamChk/tensorflowlearning/blob/main/TF_TUT_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow tutorial
---
# Section : A

In [48]:
import tensorflow as tf
import os 
import numpy as np

## Set GPU
---

In [7]:
x= tf.config.list_physical_devices('GPU')

In [9]:
for i in x:
  print(i)
tf.config.experimental.set_memory_growth(x[0],True)

PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')


## Constatnt Tensor Initialization
---

### Example 1

In [11]:
a = tf.constant(4)
print(a)

tf.Tensor(4, shape=(), dtype=int32)


### Example 2 : Shape

In [14]:
 a = tf.constant([range(1,10)],shape=(3,3))
 print(a)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


### Example 3 : Datatype

In [16]:
a = tf.constant([range(1,10)],shape=(3,3),dtype = tf.float64)
print(a)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float64)


## Type Conversion
___

In [25]:
print(f"a ->\n {a} \n {type(a)}\n" )
"""
Type Casting
----------------------------------
"""
b = tf.cast(a,dtype= tf.int32) 
"""------------------------------"""
print(f"b->\n {b} \n {type(b)}\n")

a ->
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 
 <class 'tensorflow.python.framework.ops.EagerTensor'>

b->
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 <class 'tensorflow.python.framework.ops.EagerTensor'>



## Special Tensors
---
- ones
- zeros
- eye [Identity Tenor]
- fill
---

### Ones

In [38]:
Ones = tf.ones(shape=(3,3))
print(Ones)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


### Zeros

In [39]:
zeros = tf.zeros(shape=(3,3))
print(zeros)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


### Identity

In [40]:
I = tf.eye(2 ,3)
print(I)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]], shape=(2, 3), dtype=float32)


### Fill

In [41]:
Fill = tf.fill(dims = (2,3),value= 4.2)
print(Fill)

tf.Tensor(
[[4.2 4.2 4.2]
 [4.2 4.2 4.2]], shape=(2, 3), dtype=float32)


In [42]:
#oneHot = tf.one_hot() #don't know much about it

## Distributions in TF
---
- normal
- uniform
---

### 1. Normal Distribution

In [46]:
normal_dst = tf.random.normal(mean=0,stddev=1,shape=(3,3))
print(normal_dst)

tf.Tensor(
[[ 0.10508081  0.80867183  0.55365765]
 [ 0.81430423 -0.94588    -0.46193665]
 [-0.10823865  0.6129143  -0.30011275]], shape=(3, 3), dtype=float32)


### Uniform Distribution

In [47]:
normal_dst = tf.random.uniform(minval=0,maxval=1,shape=(3,3))
print(normal_dst)

tf.Tensor(
[[0.95878065 0.00201809 0.71415114]
 [0.24132705 0.1927234  0.6156237 ]
 [0.23303294 0.3172319  0.26624167]], shape=(3, 3), dtype=float32)


## Mathematical Operations on Tensors
---
- addition
- subtraction
- divide
- multiply
- dot product
- matrics multiplication

### Addition

In [66]:
x = tf.fill((2,2), 5)
y = tf.constant([range(1,5)],shape = (2,2) )
print(f"X -> {x}\nY -> {y} \n")

X -> [[5 5]
 [5 5]]
Y -> [[1 2]
 [3 4]] 



In [52]:
z1 = tf.add(x,y)
print(z1)
z2 = x+y
print(z2) 

tf.Tensor(
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]], shape=(3, 3), dtype=int32)


### Subtract

In [54]:
z1 = tf.subtract(x,y)
print(z1)
z2 = x-y
print(z2) 

tf.Tensor(
[[ 4  3  2]
 [ 1  0 -1]
 [-2 -3 -4]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 4  3  2]
 [ 1  0 -1]
 [-2 -3 -4]], shape=(3, 3), dtype=int32)


### Divide

In [55]:
z1 = tf.divide(x,y)
print(z1)
z2 = x/y
print(z2) 

tf.Tensor(
[[5.         2.5        1.66666667]
 [1.25       1.         0.83333333]
 [0.71428571 0.625      0.55555556]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[5.         2.5        1.66666667]
 [1.25       1.         0.83333333]
 [0.71428571 0.625      0.55555556]], shape=(3, 3), dtype=float64)


### Multiply

In [56]:
z1 = tf.multiply(x,y)
print(z1)
#--------------------------
z2 = x*y
print(z2) 

tf.Tensor(
[[ 5 10 15]
 [20 25 30]
 [35 40 45]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 5 10 15]
 [20 25 30]
 [35 40 45]], shape=(3, 3), dtype=int32)


### Dot product

In [69]:
z1 = tf.tensordot(x,y,axes=1)
print(z1)
z2 = tf.tensordot(x,y,axes=2)
print()
print(z2)
print()
z0 = tf.tensordot(x,y,axes=0)
print()
print(z0)

tf.Tensor(
[[20 30]
 [20 30]], shape=(2, 2), dtype=int32)

tf.Tensor(50, shape=(), dtype=int32)


tf.Tensor(
[[[[ 5 10]
   [15 20]]

  [[ 5 10]
   [15 20]]]


 [[[ 5 10]
   [15 20]]

  [[ 5 10]
   [15 20]]]], shape=(2, 2, 2, 2), dtype=int32)


### Matrix Multiplication

In [88]:
print(x , y)
print(x@y)
M = tf.matmul(x,y)
print(M)

tf.Tensor(
[[5 5]
 [5 5]], shape=(2, 2), dtype=int32) tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[20 30]
 [20 30]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[20 30]
 [20 30]], shape=(2, 2), dtype=int32)


## Reshaping Tensors
---
[RANK AXES SHAPE](https://youtu.be/AiyK0idr4uM)

In [70]:
z1.shape

TensorShape([2, 2])

In [72]:
len(z1.shape)

2

In [85]:
print(tf.reshape(z1,shape=[4,1]))
print(tf.reshape(z1,shape=[4]))
print(tf.reshape(z1,shape=[1,2,2]))
#print(zk)

tf.Tensor(
[[20]
 [30]
 [20]
 [30]], shape=(4, 1), dtype=int32)
tf.Tensor([20 30 20 30], shape=(4,), dtype=int32)
tf.Tensor(
[[[20 30]
  [20 30]]], shape=(1, 2, 2), dtype=int32)


## Tensor Transpose
___

In [90]:
print(z)
print()
print(tf.transpose(z))

tf.Tensor(
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]], shape=(3, 3), dtype=int32)

tf.Tensor(
[[ 6  9 12]
 [ 7 10 13]
 [ 8 11 14]], shape=(3, 3), dtype=int32)
